services:
  - type: web
    name: portfolionitij
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /
